### ISSUE TITLE
Can I make a translation of this project?

### ISSUE THREAD

**Issue by thangngoc89** [juthilo/run-jekyll-on-windows#36]
I hate the legal things so as this project using  CC-BY-3.0 license. Can I translate it and publish it on my own

**Comment by juthilo** [comment]
As long as you keep all original Copyright and author references intact, yes. Feel free to ping me when you're finished; I'd be happy to link back to your translation.

(Specifically, this line shouldn't be touched: `Copyright © 2015 Julian Thilo, licensed under CC-BY-3.0.`)

**Comment by thangngoc89** [comment]
Thanks for your answer
